import json
import datetime

def log_activity(generated_text, new_state):
    """
    Logs the activity of the Live Directory.

    Parameters:
        generated_text (str): The text generated by the autogen module.
        new_state (dict): The updated state of the directory.
    """

    # Create a log entry
    log_entry = {
        'timestamp': datetime.datetime.now().isoformat(),
        'generated_text': generated_text,
        'new_state': new_state
    }

    log_file_path = "data/logs/activity.log"

    # Append the log entry to the log file
    with open(log_file_path, "a") as f:
        f.write(json.dumps(log_entry, indent=4))
        f.write("\n")

    print(f"Activity logged at {log_entry['timestamp']}")

